from __future__ import annotations

PROCEDURE_REGISTRY: list[dict] = [
    {
        "procedure_name": "get_tool_ranking",
        "description": "Ranks AI tools by observed adoption over a time range.",
        "purpose": "Identify the most used or most adopted AI tools.",
        "parameters": {"time_period": "str", "limit": "int"},
        "required_parameters": [],
        "optional_parameters": ["time_period", "limit"],
        "outputs": ["tool_id", "tool_name", "adoption_score"],
        "supported_intents": ["TOOL_RANKING", "TOOL_ADOPTION"],
        "allowed_tables": ["ai_tool_usage", "ai_tools"],
        "sensitivity": "low",
        "dependencies": [],
        "visualization_types": ["horizontal_bar", "table"],
    },
    {
        "procedure_name": "get_tool_usage_trend",
        "description": "Returns usage trend data for a specific tool over time.",
        "purpose": "Show adoption or usage movement over a period.",
        "parameters": {"tool_id": "int", "date_range": "str"},
        "required_parameters": ["tool_id"],
        "optional_parameters": ["date_range"],
        "outputs": ["tool_id", "usage_month", "usage_count"],
        "supported_intents": ["TREND_ANALYSIS", "TOOL_USAGE"],
        "allowed_tables": ["ai_tool_usage"],
        "sensitivity": "low",
        "dependencies": ["get_tool_ranking"],
        "visualization_types": ["line", "table"],
    },
    {
        "procedure_name": "get_department_adoption",
        "description": "Aggregates AI adoption by department.",
        "purpose": "Compare AI tool adoption across departments.",
        "parameters": {"time_period": "str"},
        "required_parameters": [],
        "optional_parameters": ["time_period"],
        "outputs": ["department_id", "department_name", "adoption_rate"],
        "supported_intents": ["DEPARTMENT_ANALYSIS", "TOOL_ADOPTION"],
        "allowed_tables": ["ai_tool_usage", "departments"],
        "sensitivity": "low",
        "dependencies": [],
        "visualization_types": ["bar", "table"],
    },
    {
        "procedure_name": "get_tool_adoption_forecast",
        "description": "Returns externally generated AI tool adoption forecasts.",
        "purpose": "Query ML-generated future adoption estimates for a tool.",
        "parameters": {"tool_id": "int", "forecast_months": "int"},
        "required_parameters": ["tool_id"],
        "optional_parameters": ["forecast_months"],
        "outputs": ["tool_id", "forecast_month", "predicted_adoption_rate", "lower_bound", "upper_bound", "model_version"],
        "supported_intents": ["ADOPTION_FORECAST"],
        "allowed_tables": ["ml_tool_adoption_forecast"],
        "sensitivity": "low",
        "dependencies": ["get_tool_ranking"],
        "visualization_types": ["line", "table"],
    },
    {
        "procedure_name": "get_department_adoption_risk",
        "description": "Aggregates user adoption risk by department.",
        "purpose": "Identify departments with the highest predicted adoption risk.",
        "parameters": {"prediction_month": "str"},
        "required_parameters": [],
        "optional_parameters": ["prediction_month"],
        "outputs": ["department_name", "risk_score", "risk_band"],
        "supported_intents": ["ADOPTION_RISK"],
        "allowed_tables": ["ml_user_adoption_risk", "users", "departments"],
        "sensitivity": "low",
        "dependencies": [],
        "visualization_types": ["donut", "bar"],
    },
    {
        "procedure_name": "get_user_segment_distribution",
        "description": "Returns user segment composition by department or overall population.",
        "purpose": "Summarize user segments produced by external ML segmentation.",
        "parameters": {"prediction_month": "str", "group_by": "str"},
        "required_parameters": [],
        "optional_parameters": ["prediction_month", "group_by"],
        "outputs": ["segment_name", "user_count"],
        "supported_intents": ["USER_SEGMENTATION"],
        "allowed_tables": ["ml_user_segments"],
        "sensitivity": "low",
        "dependencies": [],
        "visualization_types": ["donut", "bar"],
    },
    {
        "procedure_name": "get_usage_anomalies",
        "description": "Returns anomalies detected in usage patterns across teams and tools.",
        "purpose": "Spot unusual AI activity patterns.",
        "parameters": {"metric_date": "str", "team_id": "int"},
        "required_parameters": [],
        "optional_parameters": ["metric_date", "team_id"],
        "outputs": ["team_name", "tool_name", "anomaly_score", "is_anomaly"],
        "supported_intents": ["USAGE_ANOMALY"],
        "allowed_tables": ["ml_usage_anomalies", "teams", "ai_tools"],
        "sensitivity": "low",
        "dependencies": [],
        "visualization_types": ["line", "scatter"],
    },
    {
        "procedure_name": "get_team_productivity_forecast",
        "description": "Returns per-team productivity forecast values generated externally.",
        "purpose": "Show predicted throughput and forecast intervals for teams.",
        "parameters": {"team_id": "int", "prediction_month": "str"},
        "required_parameters": [],
        "optional_parameters": ["team_id", "prediction_month"],
        "outputs": ["team_name", "predicted_completed_story_points", "lower_bound", "upper_bound"],
        "supported_intents": ["PRODUCTIVITY_FORECAST", "PRODUCTIVITY_ANALYSIS"],
        "allowed_tables": ["ml_team_productivity_forecast", "teams"],
        "sensitivity": "low",
        "dependencies": [],
        "visualization_types": ["bar", "line"],
    },
]


def get_procedure(name: str) -> dict:
    for procedure in PROCEDURE_REGISTRY:
        if procedure["procedure_name"] == name:
            return procedure
    raise KeyError(f"Procedure '{name}' not found in registry.")


def list_procedures() -> list[dict]:
    return PROCEDURE_REGISTRY
