from __future__ import annotations

SCHEMA_KNOWLEDGE = {
    "ai_tool_usage": {
        "purpose": "Observed AI tool interactions and sessions across teams and departments.",
        "relationships": ["users", "ai_tools", "teams", "departments", "ai_tasks"],
        "grain": "One row represents a usage event or session for one user interacting with one tool.",
        "sensitivity": "low",
        "columns": {
            "usage_count": "Number of tool interactions recorded within the session.",
            "session_duration_seconds": "Time spent using the tool in the recorded session.",
            "success_flag": "Whether the recorded interaction was successful.",
        },
    },
    "ml_tool_adoption_forecast": {
        "purpose": "Future adoption estimates generated by an external ML pipeline.",
        "relationships": ["ai_tools"],
        "grain": "One row is an estimated monthly adoption rate for one tool.",
        "sensitivity": "low",
        "columns": {
            "predicted_adoption_rate": "Model-generated adoption rate estimate, not an observed measurement.",
            "lower_bound": "Lower bound of the forecast interval.",
            "upper_bound": "Upper bound of the forecast interval.",
            "model_version": "Version of the external model that generated the forecast.",
        },
    },
    "ml_user_adoption_risk": {
        "purpose": "Employee-level adoption risk scores aggregated and reported under controlled access patterns.",
        "relationships": ["users"],
        "grain": "One row is the predicted adoption risk for one user in one month.",
        "sensitivity": "restricted",
        "columns": {
            "risk_band": "Categorical risk classification: LOW, MEDIUM, HIGH.",
            "risk_score": "Probability-like risk score generated by the external model.",
        },
    },
}


def retrieve_knowledge(query: str) -> list[dict]:
    normalized = (query or "").lower()
    hits: list[dict] = []
    for table_name, metadata in SCHEMA_KNOWLEDGE.items():
        if any(keyword in normalized for keyword in (table_name.replace("_", " "), "adoption", "forecast", "tool", "usage")) or any(
            keyword in metadata["purpose"].lower() for keyword in ("usage", "adoption", "forecast", "tool")
        ):
            hits.append({"table": table_name, "metadata": metadata})
    return hits
